### PR TITLE
Add deprecation notice to readme

### PR DESCRIPTION
**Pull request by davewasmer**
In light of @krisselden's comments on #12, seems like this project might be deprecated? If that's the case, a notice in the readme might be helpful so new projects can try using an alternative approach.

Not sure if it's actually being deprecated, but figured I'd send the PR along just in case.

### CODE REVIEW

**Comment by stefanpenner** [comment]
it would be interesting to see this library evolve to work in the new world. ALthough maybe the name will no longer make sense.

thoughts @krisselden ?

**Comment by stefanpenner** [comment]
Ultimately, I do believe this will continue to work during 2.x, I don't believe any pieces that it requires are actually deprecated.

**Comment by lukemelia** [comment]
Agreed. I don't see us deprecating the library. Using it less frequently, likely, but not deprecating.

**Comment by davewasmer** [comment]
Cool, glad to hear it :smile:

**Pull request closed without merging**
