### PR TITLE
Refactoring  to work with Ember 3.14

### PR DESCRIPTION
**Pull request by averydev**
An issue with `notifyPropertyChange` not firing when properties were updated on the content[updatedProp] that came up when upgrading an app to 3.14.  

After digging in, it seemed like this mixin needed some attention.

### CODE REVIEW

**Comment by tniezurawski** [comment]
@averydev Should be fixed by https://github.com/yapplabs/ember-buffered-proxy/pull/49.

Could you verify if it works properly for you with `master`?

**Comment by averydev** [comment]
Oh!  Great!  Your PR looks much better :) I'll give it a try

**Comment by tniezurawski** [comment]
Any news @averydev? I'd like to release a new version soon so it would be great if you could confirm that it works for you as well :)

**Comment by tniezurawski** [comment]
@averydev I assume all is good :) Closing this one. Please raise a separate issue/pull request if something is still wrong. 🙌

**Pull request closed without merging**
