### PR TITLE
Update "ember-cli-babel" to v6.6.0

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @lukemelia

### CODE REVIEW

**Comment by Turbo87** [comment]
@lukemelia @stefanpenner any comments or questions?

**Comment by Turbo87** [comment]
@lukemelia do you have time to release this as a new minor version? I would like to update https://github.com/simplabs/ember-validated-form-buffer/blob/0e90a7816008b3de61c88cf97eaff15a71201d59/package.json#L23 😉

**Comment by lukemelia** [comment]
@Turbo87 released 0.8.0

**Comment by Turbo87** [comment]
thank you :)

**Pull request merged**
